utils::screen: fix for gcc 14
GCC 14 changes the implicit function warning to error, resulting in
screen build to fail with:

  pty.c error: implicit declaration of function 'openpty';

The reason is a include file collision, as there is a pty.h in the
screen sources which hides the system pty.h holding the declaration.

The reason for picking up the pty.h from sources is the include file
hack where we added $1 to the include search path. But without this the
build fails due to missing headers, so move the sources to the build
directory prior to calling autotoolsBuild to make them available.