elfutils: fix build for aarch64
Since 0.196 lib/system.h includes <fcntl.h>, which defines struct iovec
when _GNU_SOURCE is set. The aarch64 backend also includes
<linux/uio.h>, which defines it again:

  linux/uio.h:17:8: error: redefinition of 'struct iovec'

Apply upstream commit 64e89606ff49 ("backends: use <sys/uio.h> instead
of <linux/uio.h> for struct iovec").

Signed-off-by: Christian Pötzsch <christian.poetzsch@kernkonzept.com>